spring.application.name=ecoruta-api
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/ecoruta_db
spring.datasource.username=postgres
spring.datasource.password=Ajstyles4#

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=ecoruta

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false